package gaoxiao6331.commom.token

enum class Keyword(val keywordName: String) : Token {
    NamespaceKeyword("namespace"),
    IncludeKeyword("include"),
    CppIncludeKeyword("cpp_include"),
    ExceptionKeyword("exception"),
    ServiceKeyword("service"),
    ExtendsKeyword("extends"),
    RequiredKeyword("require"),
    OptionalKeyword("optional"),
    FalseKeyword("false"),
    TrueKeyword("true"),
    ConstKeyword("const"),
    DoubleKeyword("double"),
    StructKeyword("struct"),
    TypedefKeyword("typedef"),
    UnionKeyword("union"),
    StringKeyword("string"),
    BinaryKeyword("binary"),
    BoolKeyword("bool"),
    ByteKeyword("byte"),
    EnumKeyword("enum"),
    ListKeyword("list"),
    SetKeyword("set"),
    MapKeyword("map"),
    I8Keyword("i8"),
    I16Keyword("i16"),
    I32Keyword("i32"),
    I64Keyword("i64"),
    ThrowsKeyword("throws"),
    VoidKeyword("void"),
    OnewayKeyword("oneway"),
}