package gaoxiao6331.commom

enum class Keyword {
    NamespaceKeyword,
    IncludeKeyword,
    CppIncludeKeyword,
    ExceptionKeyword,
    ServiceKeyword,
    ExtendsKeyword,
    RequiredKeyword,
    OptionalKeyword,
    FalseKeyword,
    TrueKeyword,
    ConstKeyword,
    DoubleKeyword,
    StructKeyword,
    TypedefKeyword,
    UnionKeyword,
    StringKeyword,
    BinaryKeyword,
    BoolKeyword,
    ByteKeyword,
    EnumKeyword,
    SenumKeyword,
    ListKeyword,
    SetKeyword,
    MapKeyword,
    I8Keyword,
    I16Keyword,
    I32Keyword,
    I64Keyword,
    ThrowsKeyword,
    VoidKeyword,
    OnewayKeyword,
}